spring:
    profiles: test
    application:
        name: simplelog
    datasource:
        connection:
            url: ${OPENSHIFT_MONGODB_DB_HOST}:${OPENSHIFT_MONGODB_DB_PORT}
        database: simplelog
        usecredentials: yes
        user:
            name: admin
            password: 97g6nurgCk5H        
server:
    port: ${OPENSHIFT_DIY_PORT}